Feat/user role UI
Pool-Escrow/PWA pull request #96
Opened 2024-09-02 14:46 UTC by dantgw

- Added test cases for visibility of register button for admin and non-admin users
- Removed the progress bar only when pool has ended. (I tried to add test cases for progress bar as well, but ran into some issues.)

2024-09-02 14:48 UTC, ottodevs commented
<!-- deploying-comment: do not delete/edit this line -->
✅ **Deployment Complete!** 🌐
| Details | Link |
| --- | --- |
| **View Deployment** | [Visit Site](https://pwa-mcbe6p3x4-pool-team.vercel.app) |

2024-09-02 18:02 UTC, ottodevs requested changes
Looks good for now, just check if we need to use `cn` and we merge after this is clear.

Thanks for the good work!

2024-09-03 00:19 UTC, ottodevs commented
<!-- deploying-comment: do not delete/edit this line -->
✅ **Deployment Complete!** 🌐
| Details | Link |
| --- | --- |
| **View Deployment** | [Visit Site](https://pwa-bhr9rrow5-pool-team.vercel.app) |

2024-09-03 00:29 UTC, dantgw commented on src/app/pwa/(pages)/pool/new/page.tsx
> +        return <div className={cn('mt-4 w-full text-center')}>You are not authorized to create a pool.</div>
Okay, I removed it.

2024-09-03 09:24 UTC, ottodevs commented on src/app/pwa/(pages)/pool/new/page.tsx
> +        return <div className={cn('mt-4 w-full text-center')}>You are not authorized to create a pool.</div>
Thanks!

2024-09-03 09:25 UTC, ottodevs approved these changes
LGTM!

2024-09-03 09:26 UTC, merged